### ISSUE TITLE
[Feature] Specter address verification

### ISSUE THREAD

**Issue by w-i-n-s** [Sjors/nthkey-ios#10]
- [ ] Copy address from addresses tab to the clipboard for share
- [x] Verify address from Specter (scan the address from Specter and app should check if it matches) #34 
- [x] Possibility to mark the address as used (by gesture on addresses tab)

Discussion:
> Being able to select an address, copy it to clipboard and/or share, is nice.
The primary goal is to verify the address that Specter shows.
So it would be nice if we can scan the address from Specter and then say it matches.
And we should be able to mark an address as used (maybe using the swipe to delete gesture)

**Comment by Sjors** [comment]
This works quite nice now, but see #63.

I actually don't want copy-paste support here. Trusting the clipboard opens another can of worms.
