### ISSUE TITLE
Implement CoreData persistent store

### ISSUE THREAD

**Issue by w-i-n-s** [Sjors/nthkey-ios#12]
Original task:

> Implementing multi-wallet. Should use Core Data as ORM. Only unique *entropyMask* can stay in defaults for whole app. For each wallet:
    - which network (testnet, mainnet, and later also Signet)
    - the threshold (how many signatures are required)
    - information about each co-signer: their xpub and derivation path
    - a list of pre-derived addresses

**Comment by Sjors** [comment]
This is done!
