### ISSUE TITLE
App can import cosigners from old/discarded wallets (files)

### ISSUE THREAD

**Issue by w-i-n-s** [Sjors/nthkey-ios#16]
All details in the screencast. Users cannot wipe the cosigners and cannot use them. Old wallet files after deleting in Specter can be used to repeat the bug.

https://user-images.githubusercontent.com/2025621/110241485-cc387100-7f59-11eb-9e9a-47531bad0bca.mov

**Comment by Sjors** [comment]
Look like the "Wipe wallet" option is missing in your screen. This is normally below the cosigners.

But I don't understand the description. What do you mean by "Old wallet files after deleting in Specter can be used to repeat the bug."

**Comment by w-i-n-s** [comment]
@Sjors Wipe wallet button isn't missed. App don't have wallet - so, we cannot wipe it. But app has cosigners (by importing old wallet file from Specter) and because of this user cant use the app actually, issue in incostintency of the model checks. I'll fix it in terms of change model store in https://github.com/Sjors/nthkey-ios/issues/12

**Comment by Sjors** [comment]
Thanks

**Comment by Sjors** [comment]
I guess this is fixed?

**Comment by w-i-n-s** [comment]
@Sjors Yes, I cannot import old wallet (app instance can't be a part of it) in both cases:
- [x] we don't have any wallets yet
<img width="170" alt="Снимок экрана 2021-04-22 в 22 59 02" src="https://user-images.githubusercontent.com/2025621/115777729-5760af80-a3be-11eb-935d-753765d12c61.png">

- [x] some wallets already here
<img width="171" alt="Снимок экрана 2021-04-22 в 22 57 30" src="https://user-images.githubusercontent.com/2025621/115777559-208a9980-a3be-11eb-8b1e-2e4cb0fcdb9d.png">
