### ISSUE TITLE
Crash on "Recover from backup"

### ISSUE THREAD

**Issue by w-i-n-s** [Sjors/nthkey-ios#21]
Can be repeated on Master's d0a794e95f7b38dcdf4a6118341be266f11f3ab8
Details on screencast

https://user-images.githubusercontent.com/2025621/110802949-5bf65c00-8287-11eb-8988-37041d00b994.mov

**Comment by w-i-n-s** [comment]
@Sjors will be fixed in change architecture to MVVM in #11. Short description of the bug - whole app redraws (because of wrong "god object" AppState will change) and AppState object isn't set as an environmental one.

**Comment by Sjors** [comment]
I'm assuming this is fixed.
