### ISSUE TITLE
Previews: add draft transaction to SignView 

### ISSUE THREAD

**Issue by Sjors** [Sjors/nthkey-ios#24]
<img width="1150" alt="Schermafbeelding 2021-03-28 om 17 50 58" src="https://user-images.githubusercontent.com/10217/112758343-3048d500-8fee-11eb-9c20-d86222cad0fc.png">

**Comment by w-i-n-s** [comment]
@Sjors 
Should the app store all signed transactions inside? 

Like this flow:
1. User ca add one (PSBT) with QR or import `*.PSBT` file
2. User can sign it
3. User can export it by QR/file
Anyway, the transaction will be saved inside the list

**Comment by Sjors** [comment]
For the time being let's not store the transaction.

**Comment by w-i-n-s** [comment]
Okay, then just I'll add one signed transaction to check export UI

**Comment by w-i-n-s** [comment]
fixed in fd9334b
