### ISSUE TITLE
Add Signet

### ISSUE THREAD

**Issue by Sjors** [Sjors/nthkey-ios#26]
I'd like to add Signet support:

<img width="393" alt="Schermafbeelding 2021-04-05 om 12 55 36" src="https://user-images.githubusercontent.com/10217/113567094-3b16f180-960e-11eb-9f2d-e566370dfcb0.png">

Signet is identical to testnet in terms of addresses and transaction signature. So internally LibWally can be used with `.testnet` and the same with Specter.

**Comment by w-i-n-s** [comment]
@Sjors Export is ready but on import the wallet, we should ask a user about which network wallet contains. https://github.com/Sjors/nthkey-ios/pull/37
<img width="516" alt="signetQR" src="https://user-images.githubusercontent.com/2025621/115792552-29d23100-a3d3-11eb-8dc2-83c49270d5fc.png">

**Comment by Sjors** [comment]
Agreed, I left a suggestion for that UI: https://github.com/Sjors/nthkey-ios/pull/37#pullrequestreview-643065644 (we can improve it later of course)

**Comment by w-i-n-s** [comment]
Completed in c0718eac53f739d1800e18e4d04a7b1029357a09
