### ISSUE TITLE
Mark addresses as used

### ISSUE THREAD

**Issue by Sjors** [Sjors/nthkey-ios#29]
A user should be able to mark an addresss as used, so they're reminded to not use it again. Maybe with a swipe gesture, confirmed with "mark as used?", similar to how delete works in a tableview.

We should not hide the address. A light strike-through is probably good enough.

**Comment by w-i-n-s** [comment]
Before bump project, to iOS 15 we can use default `.onDelete(...)` modifier to mark address as used. After it we'll use [`.swipeActions(...)` modifier ](https://developer.apple.com/documentation/swiftui/texteditor/swipeactions(edge:allowsfullswipe:content:)?changes=latest_minor)
