### ISSUE TITLE
Minor issues to fix before AppStore release

### ISSUE THREAD

**Issue by w-i-n-s** [Sjors/nthkey-ios#49]
Purchase flow need loaders between screens and additional notifications which allow user to understand what happen (and debug purpose)
![IMG_7336](https://user-images.githubusercontent.com/2025621/119873030-c46ee400-bf2c-11eb-9615-d9aafdaeb76a.PNG)
~- [ ] Loader in 2-3~
~- [ ] Loader in 3-4~
~- [ ] Implement Status view for display `purchasePublisher` value~
~- [ ] Check additional `SKPaymentTransactionObserver` methods if it can help in UX improvements~
[edit] Doen't make sense after 0c9ed453b193eee46084dd2604b3cb53620ba0ec

---
_Originally posted by @Sjors in https://github.com/Sjors/nthkey-ios/issues/44#issuecomment-849494464_

>I was able to make a purchase using the sandbox user. However the "Use real Bitcoin (mainnet)" dialog doesn't close when the purchase is complete.

- [x] Close the dialog when user make payment e0e0df0954f5255593e98049c4503991701b631c

>I also suggest making the "Subscribe Now" button grey while the purchase is in progress.

- [x] Change UI color 0c9ed453b193eee46084dd2604b3cb53620ba0ec

> I see, but a month is not 30 days, so that bit has to be more accurate.
> Right, so we just check if: current time > expirationDateFromResponse (stored in UserDefaults)

- [x] check current calendar and set the date according to it 258c96ba3825480d9634c7de48b5feb8ae18e028
- [x] Ask status after this date da8f237939cca662cbbe9d93e51e3798d1c3474f

> So we do something like this?
> 1. When user makes a purchase, store the expiration date
> 2. When app wakes up check if time > expiration date
> 3. When time > experitation date, fetch (???) from Apple:
>   a) update expiration date (??)
>   b) turn off subscription if it wasn't renewed
> (if connection to Apple fails, just ignore and try later)
<img width="222" alt="Снимок экрана 2021-06-03 в 21 39 41" src="https://user-images.githubusercontent.com/2025621/120696022-b84acf80-c4b4-11eb-8bc2-63b925c19a7f.png">

---

> Only minor suggestion (can wait): when the purchase (or restore) is complete, jump to the mainnet tab. If it's easier: do this for both the Announce and Import sections.
- [x] mark requested tab after purchase 1cc14fb0378f6e7b0f25ac221101160de9ebf97c

**Comment by Sjors** [comment]
When the user does not have a subscription and they airdrop (or open via files) a transaction, make sure the sign button is also disabled and the user is prompted to subscribe.

**Comment by w-i-n-s** [comment]
> When the user does not have a subscription and they airdrop (or open via files) a transaction, make sure the sign button is also disabled and the user is prompted to subscribe.

@Sjors 
Based on the current [implementation](https://github.com/Sjors/nthkey-ios/blob/53156e8f87889e35acf327a97c9876187e648aea/NthKey/View/Sign/SignView.swift#L21) user should have an active subscription to load or scan mainnet's PSBT. 

So, we overview the next case: user open import dialog and after that the subscription isn't active anymore. User can load psbt but the app should not allow to sign without active subscription. Just clearify the case.

**Comment by Sjors** [comment]
When there is no subscription, it should not process or show the PSBT.
