### ISSUE TITLE
Fix handling large QR code

### ISSUE THREAD

**Issue by Sjors** [Sjors/nthkey-ios#51]
When a transaction has several inputs it seems to get too large for our current QR generating code:

```
 [filter] initQRCodeForInputByteSize cannot find proper rs block info (input data too big?)
```

![IMG_8024](https://user-images.githubusercontent.com/10217/120187292-e611e900-c214-11eb-83aa-721902047031.jpg)

**Comment by Sjors** [comment]
If this is complicated to fix, then let's at least display a clear error message: "PSBT is too large to display as a QR code"

**Comment by w-i-n-s** [comment]
limits https://stackoverflow.com/a/51242715/1067147
