### ISSUE TITLE
Display current wallet on sign screen

### ISSUE THREAD

**Issue by Sjors** [Sjors/nthkey-ios#53]
If there is more than 1 wallet, display the currently selected wallet name on the sign screen. This reduces confusion if sign button is disabled (but we should also improve error messages there).

**Comment by w-i-n-s** [comment]
Fixed in 7259aa7a0ef0bdf77b533148b520f5ae3c27bdcc
[<img src="https://cdn.zappy.app/54a7ba3daf294889a90a859852b80184.gif">](gif)

**Comment by Sjors** [comment]
Looks great
