### ISSUE TITLE
Sign screen doesn't fit on small device

### ISSUE THREAD

**Issue by Sjors** [Sjors/nthkey-ios#55]
E.g. iPod Touch 7th generation simulator:

<img width="366" alt="Schermafbeelding 2021-06-03 om 16 50 49" src="https://user-images.githubusercontent.com/10217/120665290-ed8ef780-c48b-11eb-8f66-51b1cc313838.png">

**Comment by w-i-n-s** [comment]
@Sjors Not only this screen should be fixed. I'll check them all
![Simulator Screen Shot - iPod touch (7th generation) - 2021-06-12 at 16 16 35](https://user-images.githubusercontent.com/2025621/121777244-c32eef80-cb99-11eb-9807-d4e899a464e9.png)
